# Define the docker compose version
version: '3.9'

# Add the images of my application
services: 
  # Configuration of my current project
  price-tracking-scrapping:
    # Specify the address of the dockerfile
    build: 
      context: .
      dockerfile: dockerfile

    # Define the name of the image of my app
    image: price-tracking-scrapping:latest
    
    # Define the container name of my service
    container_name: price-tracking-scrapping
    
    # Definy the port mapping
    ports:
      - "3002:3002"
    networks:
      - price-tracking-network

  
networks:
  price-tracking-network:
    name: price-tracking-network

